#!/bin/bash

# start the script
echo 'Welcome to Bisen Appa Installing now...'

# check if latex is installed
installed=`which latex`

# if no latex has been installed

if [ ! -n "$installed" ]; then

		#install texfull-live
		sudo apt-get install texlive-full
        echo 'installing linux'
fi

echo 'latex has been installed'
# also check if git has been installed
if [ ! -f /usr/bin/git ]; then
	
		# install git
		sudo apt-get install git

fi

# move template to /etc/appa folder
echo 'making a folder in ~/.appa/'
mkdir ~/.appa
mkdir ~/.appa/src/
mkdir ~/.appa/src/science
mkdir ~/.appa/src/blank

echo 'copying source files into /etc/appa'
cp -r src/blank/* src/Makefile ~/.appa/src/blank/
cp -r src/science/* src/Makefile ~/.appa/src/science/

# copy appa script into /usr/local/bin
echo 'copying appa to /usr/local/bin'
sudo cp bin/appa /usr/local/bin

# done
echo 'Installation finished.'
